### ISSUE TITLE
Clean abort() of the simulation

### ISSUE THREAD

**Issue by alessandropellegrini** [ROOT-Sim/core#1]
`core_abort()` in `core/core.c` jumps to a context related to a function which already returned, thus entering undefined behavior.

**Comment by brimobile1** [comment]
> `core_abort()` in `core/core.c` jumps to a context related to a function which already returned, thus entering undefined behavior.

**Comment by alessandropellegrini** [comment]
This is no longer relevant, as was silently fixed in the latest releases.
