### ISSUE TITLE
Additional message fields for easier debug

### ISSUE THREAD

**Issue by Piccions** [ROOT-Sim/core#11]
We want to add more fields to the message struct (possibly only in debug runs) in order to ease the process of debugging a model.
For example, the sending time and the id of the sending LP could be very useful.

**Comment by alessandropellegrini** [comment]
@Piccions am I wrong or this has been completed?

**Comment by Piccions** [comment]
You are right; this specific issue has been completed. I still feel like we may need some more debugging aid, but if I come up with something I'll open a new issue. Thanks for noticing!
