### ISSUE TITLE
Message allocator behaves inconsistently

### ISSUE THREAD

**Issue by AdrianoPi** [ROOT-Sim/core#65]
The message allocation function msg_allocator_alloc sets msg->pl_size only in 2 of the 3 code paths.
https://github.com/ROOT-Sim/core/blob/4f83b7466d5dc5767fbf9d00eccdaf37745f8677/src/mm/msg_allocator.c#L48-L62

We have to decide whether it is responsibility of msg_allocator_alloc to set msg->pl_size, or not.

**Comment by Piccions** [comment]
I would say the message allocator has writing responsibility on ```pl_size```, since it is also used internally to determine how to free the message: https://github.com/ROOT-Sim/core/blob/4f83b7466d5dc5767fbf9d00eccdaf37745f8677/src/mm/msg_allocator.c#L68-L74

**Comment by Piccions** [comment]
Perfect; since we agree, I opened a PR addressing your suggestion. Have a look at it to see if it convinces you. Thanks for reporting this issue!
