### ISSUE TITLE
Wrong cROOT-Sim link

### ISSUE THREAD

**Issue by AdrianoPi** [ROOT-Sim/core#67]
The domain is misspelled in the readme URL for cROOT-Sim: `gihub` instead of `github`

https://github.com/ROOT-Sim/core/blob/2277d9ce5cf2caf0057632bbc13318b6467d36ac/README.md?plain=1#L39
https://github.com/ROOT-Sim/core/blob/2277d9ce5cf2caf0057632bbc13318b6467d36ac/README.md?plain=1#L78

**Comment by alessandropellegrini** [comment]
Thanks! I'll take care of this in the next merge window.
