### ISSUE TITLE
Test threadpool race condition which negates concurrency

### ISSUE THREAD

**Issue by Piccions** [ROOT-Sim/core#70]
The test threadpool doesn't guarantee actual multi threaded execution.

https://github.com/ROOT-Sim/core/blob/bcd1eddeb13ab543e13dd4c4e6b13c43401d5c6c/test/framework/thread.c#L67-L74

As shown here, a thread can complete a task execution before another thread has taken the semaphore at line 68; that means that it can happen, for example, that a single thread is able to sequentially execute all the tasks thus negating any kind of real concurrency.
We obviously need thread barriers here.

As a side note: we are using OS level semaphores as a synchronization primitive here, while we could use simpler and easier to test alternatives, e.g.: condition variables.

**Comment by alessandropellegrini** [comment]
Of course you are right, and I remember that I fixed this months ago, but apparently that fix never went into the repository... :scream: 

Let me see if I can find the commit resting in peace in some random piece of hardware that I have occasionally been using. Or, if I don't find it, I'll rewrite the patch.

I also agree on condition variables, but let's discuss whether it's a priority now.

**Comment by Piccions** [comment]
Condition variables are definitely not a priority, but the correctness of the test framework is. The statistic subsystem tests implemented in #74 depends on this one.

**Comment by alessandropellegrini** [comment]
I'll take care of this asap I hope.

Anyways, I was also thinking that a pure barrier might be suboptimal, as it may make sense to have one worker carry out more work than others.

Anyhow it'll be sufficient for now!

**Comment by Piccions** [comment]
I don't think we want to maximize throughput or performance during testing, rather we want to maximize concurrency in order to break things. That's why I think a barrier (or any equivalent construct) is the correct choice here.

**Comment by alessandropellegrini** [comment]
I was thinking about exploring concurrency patterns different from fork/join in tests, not for performance. It may make sense to have an imbalance in the number of actions that a worker is doing, or having a worker re-enter a task while others have not yet finished the previous.

**Comment by Piccions** [comment]
I understand what you mean and it may make sense; in this case, the only feature that we are missing is the setting of the ```rid```. Right now, a thread reentering a task would reuse its old ```rid``` and that obviously breaks things.

**Comment by alessandropellegrini** [comment]
Yes it makes sense. Anyhow we should first see if we find a use case for this feature. In the meanwhile let's stick with the barrier.
